---
- name: Pull the client image
  community.docker.docker_image:
    name: "mwaniki21/client:v1.0.0"
    source: pull

- name: Pull the backend image
  community.docker.docker_image:
    name: "mwaniki21/client:v1.0.0"
    source: pull

- name: Create a folder
  ansible.builtin.file:
    path: "viper0418/client:v1.0.0"
    state: directory

- name: Copy docker-compose file from repo to folder
  ansible.builtin.template:
    src: "../docker-compose.yml"
    dest: "../docker-compose.yml"

- name: Start containers
  shell: "docker-compose up -d"
  args:
    chdir: "../"